imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
            mrappsBackendLanguages: "@mrapps.backend.languages"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: 5.6
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:
        type: file
        path: '%kernel.root_dir%/spool'

monolog:
   handlers:
       main:
           type:         fingers_crossed
           action_level: error
           handler:      grouped
       grouped:
           type:    group
           members: [streamed, deduplicated]
       streamed:
           type:  stream
           path:  "%kernel.logs_dir%/%kernel.environment%.log"
           level: debug
       deduplicated:
           type:    deduplication
           handler: swift
       swift:
           type:       swift_mailer
           from_email: 'noreply@skeleton.it'
           to_email:   ['samuele@mr-apps.com', 'luca@mr-apps.com']
           subject:    'Errore! %%message%%'
           level:      error
           formatter:  monolog.formatter.html
           content_type: text/html


# Fos User
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User


# Liip Imagine configuration
liip_imagine:
    driver:    imagick
    resolvers:
            default:
                web_path:
                    cache_prefix: uploads/cache
    filter_sets:
        backend_thumbnail:
            quality: 85
            format: jpeg
            filters:
                relative_resize: { widen: 500 }
                background: { color: '#FFFFFF' }


mrapps_backend:
    default_routes:
        - { role: DEFAULT, name: app_contatti_list }
    custom_css: ~
    logo_path: bundles/app/img/logo.png
    temp_folder: temp
    gmaps_api_key: ~
    file_accepted_types:
       image: image/jpeg, image/jpg, image/png, image/gif
       video: video/quicktime, video/mp4, video/mpeg, video/x-msvideo, video/3gpp
       pdf: application/pdf, x-pdf, application/vnd.pdf, text/pdf
       zip: application/zip, application/octet-stream
       json: application/json, text/plain, text/json
    customization:
       primary_color: '#B03843'
       text_on_primary_color: '#FFFFFF'
       text_hover_on_primary_color: '#999999'
       secondary_color: '#000000'
       text_on_secondary_color: '#FFFFFF'
       text_hover_on_secondary_color: '#999999'