# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:             ROLE_USER
        ROLE_SUPER_ADMIN:       ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            switch_user: { role: ROLE_ADMIN }
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path:  fos_user_security_login
                check_path:  fos_user_security_check
                default_target_path: mrapps_backend_index

            logout:
                target: fos_user_security_login
                invalidate_session: false
            anonymous:    true

    access_control:
        - { path: ^/panel, roles: [ROLE_ADMIN]}
        - { path: ^/register, roles: [ROLE_ADMIN] }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: [ROLE_ADMIN] }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY}